name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 4.1.0
homepage: https://github.com/bluefireteam/audioplayers
repository: https://github.com/bluefireteam/audioplayers/tree/master/packages/audioplayers
publish_to: none
flutter:
  plugin:
    platforms:
      android:
        default_package: audioplayers_android
      ios:
        default_package: audioplayers_darwin
      linux:
        default_package: audioplayers_linux
      macos:
        default_package: audioplayers_darwin
      web:
        default_package: audioplayers_web
      windows:
        default_package: audioplayers_windows

dependencies:
  audioplayers_android: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_android-4.0.3'
  audioplayers_darwin: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_darwin-5.0.2'
  audioplayers_linux: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_linux-3.1.0'
  audioplayers_platform_interface: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_platform_interface-5.0.1'
  audioplayers_web: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_web-4.1.0'
  audioplayers_windows: 
    git: 
      url: 'https://github.com/RookiePlayers/audioplayers_windows-3.1.0'
  file: ^6.1.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  meta: ^1.7.0
  path_provider: ^2.0.12
  synchronized: ^3.0.0
  uuid: ^3.0.7

dev_dependencies:
  dartdoc: ^6.1.5
  flame_lint: ^0.2.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

